language: php

dist: precise

php:
  - 7.0
  - 7.2
  - 7.3
addons:
mariadb: 10.1

#cache:
 #directories:
  #    -node_modules
   #   -vendor

before_script:
  #- cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE pings;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate #--no-interaction -vvv
notifications:
 email: kelvinkiyingi15@gmail.com 
  
script:
   -vendor/bin/phpunit
